config/routes.rb
Rails.application.routes.draw do

devise_for :artists, :controllers => { :registrations => 'artists/registrations' }

resources :artists do
resources :mixtapes do
	resources :songs
    get :autocomplete_mixtape_title, :on => :collection
	member do
		put "upvote", to: "mixtapes#upvote"
		put "downvote", to: "mixtapes#downvote"
end

get '/download', to: 'mixtapes#download'
end
end

resources :songs

resources :mixtapes

root 'mixtapes#home'

get '/download', to: 'mixtapes#download'

get '/singles', to: 'songs#index'

get "search/query"

get 'search/results', to: 'search#results'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
has_many :mixtapes
has_many :songs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/artists/confirmations_controller.rb
class Artists::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/artists/omniauth_callbacks_controller.rb
class Artists::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/artists/passwords_controller.rb
class Artists::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/artists/registrations_controller.rb
class Artists::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  def after_sign_up_path_for(resource)
    edit_artist_registration_path
  end

  # GET /resource/edit
  def edit
    super
    @artist = current_artist
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/artists/sessions_controller.rb
class Artists::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/artists/unlocks_controller.rb
class Artists::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
before_action :find_artist, only: [:destroy]
impressionist :actions=>[:show]

def index
	@artists = Artist.all
end

def home
    @artists = Artist.all
    
end

def new
	@artist = Artist.new
end

def create
    @artist = Artist.new(artist_params)
    if @artist.save
    	redirect_to edit_artist_path(@artist)
    else
    	render 'new'
    end
end


def show
	@artist = Artist.find(params[:id])
    @mixtapes = @artist.mixtapes.all

end

def destroy
	@artist.destroy
    redirect_to root_path
end

def edit
    @artist = current_artist
    @mixtapes = @artist.mixtapes.all 
end

def update
    @artist = Artist.find(params[:id])
    if @artist.update(artist_params)
       redirect_to artist_path(@artist)
        else
        render 'new'
    end
end

def load_suggestions
  @suggestions = Artist.select(:title) or Artist.find(:all) #Select the data you want to load on the typeahead.
  render json: @suggestions
end


def upvote
    @artist = Artist.find(params[:id])
    @Artist.upvote_by current_user
    redirect_to artist_path(@artist)
end

def downvote
    @artist = Artist.find(params[:id])
    @Artist.downvote_by current_user
    redirect_to artist_path(@artist)
end


    private

        def artist_params
            params.require(:artist).permit(:name)
        end

        def find_mixtape
            @artist = Artist.find(params[:id])
        end

        def find_radio
            @artist = Artist.last
        end

end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/edit.html.erb
<div id="bg" class="large-12 columns" style="background-color: grey;"></div>
<div id="yieldcontainer" class="row large-12 columns" style="color: black;">
<h1 style="color: white;"><%= @artist.name %></h1>
<div id="mixtapelistcontainer">
<ul id="mixtapelistedit">
<% if @mixtapes.present? %>
   <% @mixtapes.each do |mixtape| %>

  <li class="mixtapelistitem row large-12 columns">

    <div id="mixtapelistav" class="float-left">
       <%= image_tag(mixtape.mixtape_av) %>
    </div>

    <div class="float-left">
       <%= mixtape.title %>
    </div>

       <%= link_to "Delete", artist_mixtape_path(mixtape.artist, mixtape), method: :delete, data: { confirm: "Are you sure?" } %>
  
  </li>

   <br />
<% end %>
<% end %>
</ul>
</div>

<%= form_for([@artist, @artist.mixtapes.build], :html => {:id => "commentsform", :class => "row large-12 columns float-left"}) do |f| %>

  <%= f.label :title %>:
  <%= f.text_field :title %><br />

  <%= f.label :mixtapeav %>
  <%= f.file_field :mixtape_av %><br />


  <%= f.label :tracksamount %>
  <%= f.number_field :tracksamount %>

  <%= f.submit %>

<% end %>

app/views/artists/show.html.erb
<div id="masterplayer">
<div id="bg" class="large-12 columns" style="background-color: lightgrey;"></div>

	 <div id="yieldcontainer" class="row large-12 columns float-center">
        <div id="indexpadding" class="alpha60"> 


        <div id="headerwrapper" class="row large-12 columns">
        <div id="desktopblank" style="height: 80px;" class="row medium-12 columns show-for-medium"></div>
        <div id="mobileblank" style="height: 13px" class="row small-12 columns hide-for-medium"></div>
         <div id="mixtapeartist" class="row large-12 small-12 columns float-left"><b><%= link_to "#{@artist.name}", artist_path(@artist) %></b>
         <div id="mbloginbtn" class="float-right"></div>
         <div id="mbloginbtn" class="float-right"></div>
         <div id="mbloginbtn" class="float-right"></div>
         </div>

              <div id="artistsmixtapeswrap" class="row large-9 small-9 columns float-right">
                                <% if @mixtapes.present? %>
                  <% @mixtapes.each do |mixtape| %>
                    <div class="mixtapecontainer byartist float-left">
                       <%= link_to mixtape, method: :get do %>
                      <div class="avatarcontainer float-center">
                           <%= image_tag(mixtape.mixtape_av) %>
                           <span class="titleshow show-for-large">
                           <%= mixtape.title %>
                           </span>
                      </div>

                     <% end %>
                  </div>
              <% end %>
                  <% end %>
              </div>


        </div>

<div style="height: 1000px; width: 500px;"></div>

        </div>
	 </div>

<%= render "layouts/footplayer" %>

</div>