config/routes.rb
Rails.application.routes.draw do

devise_for :artists, :controllers => { :registrations => 'artists/registrations' }

resources :artists do
resources :mixtapes do
	resources :songs
    get :autocomplete_mixtape_title, :on => :collection
	member do
		put "upvote", to: "mixtapes#upvote"
		put "downvote", to: "mixtapes#downvote"
end

get '/download', to: 'mixtapes#download'
end
end

resources :songs

resources :mixtapes

root 'mixtapes#home'

get '/download', to: 'mixtapes#download'

get '/singles', to: 'songs#index'

get "search/query"

get 'search/results', to: 'search#results'

end

app/models/mixtape.rb
class Mixtape < ActiveRecord::Base
belongs_to :artist
has_many :songs, dependent: :destroy
	mount_uploader :mixtape_av, MixtapeAvUploader
	mount_uploader :archive, ArchiveUploader
has_many :comments
acts_as_votable
is_impressionable

searchable do
	text :title
end

accepts_nested_attributes_for :songs

end

app/controllers/mixtapes_controller.rb
class MixtapesController < ApplicationController
before_action :find_mixtape, only: [:destroy]
impressionist :actions=>[:show]
 include ActionController::Streaming
 include Zipline

def index
    @search = Mixtape.search do
        fulltext params[:search]
    end
	@mixtapes = @search.results
end

def home
    @mixtapes = Mixtape.all
    
end
 
def new
    @artist = current_artist
	  @mixtape = @artist.mixtapes.new
    @mixtape.mixtape_av = params[:file]

end

   def create
    @artist = current_artist
    @mixtape = @artist.mixtapes.create(mixtape_params)

    if @mixtape.save
        redirect_to edit_artist_mixtape_path(@artist, @mixtape)
    else
        render 'new'
    end
   end


   def destroy
      @mixtape.destroy
      redirect_to artist_path(@artist)
   end


def strona
  
end

def show
	@mixtape = Mixtape.find(params[:id])
    @artist = @mixtape.artist
    @artistsmixtapes = @artist.mixtapes.all.where.not(id: @mixtape.id)
    @songs = @mixtape.songs.all
    @background = @mixtape.mixtape_av.url
    impressionist(@mixtape)
    respond_to do |format|
      format.html
      format.js
    end

end


def edit
    @mixtape = Mixtape.find(params[:id])
    @songs = @mixtape.songs.all
    @tracksamount = @mixtape.tracksamount
end

def update
    @mixtape = Mixtape.find(params[:id])
    if @mixtape.update(mixtape_params)
       redirect_to mixtape_path(@mixtape)
        else
        render 'new'
    end
end

def load_suggestions
  @suggestions = Mixtape.select(:title) or Mixtape.find(:all) #Select the data you want to load on the typeahead.
  render json: @suggestions
end


def upvote
    @mixtape = Mixtape.find(params[:id])
    @mixtape.upvote_by current_user
    redirect_to mixtape_path(@mixtape)
end

def downvote
    @mixtape = Mixtape.find(params[:id])
    @mixtape.downvote_by current_user
    redirect_to mixtape_path(@mixtape)
end


def download
  @mixtape = Mixtape.find(params[:mixtape_id])
  url = @mixtape.archive.url
  @mixtape.downloadscount += 1
  @mixtape.save
    redirect_to(url)
end

    private

        def mixtape_params
            params.require(:mixtape).permit(:id, :title, :artist_id, :mixtape_av, :archive, :downloadscount, :tracksamount, songs_attributes: [:id, :title, :trackid, :audio])
        end

        def find_mixtape
            @mixtape = Mixtape.find(params[:id])
        end



        def find_radio
            @mixtape = Mixtape.last
        end

        def song_params
            params.require(:song).permit(:title, :trackid, :audio)     
        end

end

app/helpers/mixtapes_helper.rb
module MixtapesHelper
end

app/views/mixtapes/_player.html.erb
<div class="sm2-bar-ui flat">

 <div id="playercontrols" class="bd sm2-main-controls " style="display: none; border-radius: 5px;">

  <div class="sm2-inline-texture"></div>
  <div class="sm2-inline-gradient"></div>

  <div id="playerprevbtn" class="sm2-inline-element sm2-button-element playerbtncl float-left show-for-medium">
   <div class="sm2-button-bd">
    <a href="#prev" title="Previous" class="sm2-inline-button previous">&lt; previous</a>
   </div>
  </div>

  <div class="sm2-inline-element sm2-button-element playerbtncl float-left">
   <div class="sm2-button-bd">
    <a href="#play" class="sm2-inline-button play-pause">Play / pause</a>
   </div>
  </div>

  <div id="playernextbtn" class="sm2-inline-element sm2-button-element playerbtncl float-left show-for-medium">
   <div class="sm2-button-bd">
    <a href="#next" title="Next" class="sm2-inline-button next">&gt; next</a>
   </div>
  </div>


  <div id="playerhider">

  <div class="sm2-inline-element sm2-inline-status">

   <div class="sm2-playlist hide-for-small-only">
    <div class="sm2-playlist-target"><ul class="sm2-playlist-bd"></ul></div>
   </div>

   <div class="sm2-progress hide-for-small-only">
    <div class="sm2-row">
    <div class="sm2-inline-time">0:00</div>
     <div class="sm2-progress-bd">
      <div class="sm2-progress-track">
       <div class="sm2-progress-bar"></div>
       <div class="sm2-progress-ball"><div class="icon-overlay"></div></div>
      </div>
     </div>
     <div class="sm2-inline-duration">0:00</div>
    </div>
   </div>
  </div>

  </div>

 </div>

 <div style="height: 100%;" class="bd sm2-playlist-drawer sm2-element">

  <div class="sm2-inline-texture">
   <div class="sm2-box-shadow"></div>
  </div>

  <!-- playlist content is mirrored here -->

<%= render 'playlist' %>

  <div class="sm2-extra-controls">

   <div class="bd">

    <div class="sm2-inline-element sm2-button-element">
     <a href="#prev" title="Previous" class="sm2-inline-button previous">&lt; previous</a>
    </div>

    <div class="sm2-inline-element sm2-button-element">
     <a href="#next" title="Next" class="sm2-inline-button next">&gt; next</a>
    </div>

    <!-- not implemented -->
    <!--
    <div class="sm2-inline-element sm2-button-element disabled">
     <div class="sm2-button-bd">
      <a href="#repeat" title="Repeat playlist" class="sm2-inline-button repeat">&infin; repeat</a>
     </div>
    </div>

    <div class="sm2-inline-element sm2-button-element disabled">
     <a href="#shuffle" title="Shuffle" class="sm2-inline-button shuffle">shuffle</a>
    </div>
    -->

   </div>

  </div>

 </div>

</div>

app/views/mixtapes/_playlist.html.erb
  <div class="sm2-playlist-wrapper">
    
    <ul class="sm2-playlist-bd">
     <!-- item with "download" link -->
     <% @songs.each do |song| %>
      
      <li>
      <%= link_to song.audio.url, :title => "#{song.trackid} - #{song.title}", :class => "playlistlink" do %>
      <span class="redfont"><%= song.trackid %> - <%= song.title %></span>
      <% end %>
      <%= link_to "#", song.audio.url, :title => "#{song.trackid} - #{song.title}", :class => "playlistdllink sm2-exclude" %>
      </li>

     <% end %>

    </ul>
  
  </div>

app/views/mixtapes/_radio.html.erb
<div class="sm2-bar-ui flat">

 <div class="bd sm2-main-controls" style="border-radius: 5px;">

  <div class="sm2-inline-texture"></div>
  <div class="sm2-inline-gradient"></div>

  <div id="playerprevbtn" class="sm2-inline-element sm2-button-element playerbtncl float-left">
   <div class="sm2-button-bd">
    <a href="#prev" title="Previous" class="sm2-inline-button previous">&lt; previous</a>
   </div>
  </div>

  <div class="sm2-inline-element sm2-button-element playerbtncl float-left">
   <div class="sm2-button-bd">
    <a href="#play" class="sm2-inline-button play-pause">Play / pause</a>
   </div>
  </div>

  <div id="playernextbtn" class="sm2-inline-element sm2-button-element playerbtncl float-left">
   <div class="sm2-button-bd">
    <a href="#next" title="Next" class="sm2-inline-button next">&gt; next</a>
   </div>
  </div>


  <div id="playerhider">

  <div class="sm2-inline-element sm2-inline-status">

   <div class="sm2-playlist hide-for-small-only">
    <div class="sm2-playlist-target"><ul class="sm2-playlist-bd"></ul></div>
   </div>

   <div class="sm2-progress hide-for-small-only">
    <div class="sm2-row">
    <div class="sm2-inline-time">0:00</div>
     <div class="sm2-progress-bd">
      <div class="sm2-progress-track">
       <div class="sm2-progress-bar"></div>
       <div class="sm2-progress-ball"><div class="icon-overlay"></div></div>
      </div>
     </div>
     <div class="sm2-inline-duration">0:00</div>
    </div>
   </div>
  </div>

  </div>

 </div>

 <div style="height: 100%;" class="bd sm2-playlist-drawer sm2-element">

  <div class="sm2-inline-texture">
   <div class="sm2-box-shadow"></div>
  </div>

  <!-- playlist content is mirrored here -->

<%= render 'playlist' %>

  <div class="sm2-extra-controls">

   <div class="bd">

    <div class="sm2-inline-element sm2-button-element">
     <a href="#prev" title="Previous" class="sm2-inline-button previous">&lt; previous</a>
    </div>

    <div class="sm2-inline-element sm2-button-element">
     <a href="#next" title="Next" class="sm2-inline-button next">&gt; next</a>
    </div>

    <!-- not implemented -->
    <!--
    <div class="sm2-inline-element sm2-button-element disabled">
     <div class="sm2-button-bd">
      <a href="#repeat" title="Repeat playlist" class="sm2-inline-button repeat">&infin; repeat</a>
     </div>
    </div>

    <div class="sm2-inline-element sm2-button-element disabled">
     <a href="#shuffle" title="Shuffle" class="sm2-inline-button shuffle">shuffle</a>
    </div>
    -->

   </div>

  </div>

 </div>

</div>

app/views/mixtapes/edit.html.erb
<div id="bg" class="large-12 columns" style="background-color: grey;"></div>
<div id="yieldcontainer" class="row large-12 columns" style="color: black;">
<div id="uploadlistcontainer">
<% if @songs.present? %>
   <% @songs.each do |song| %>
   <%= song.trackid %>
   <%= song.title %>
   <br />
<% end %>
<% end %>
</div>
<ul id="edittracklist" style="margin-top: 50px;">
<%= form_for @mixtape do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />

  <%= f.label :mixtapeav %>
  <%= f.file_field :mixtape_av %><br />

  <%= f.label :tracksamount %>
  <%= f.number_field :tracksamount %>

  <%= f.submit %>
<% end %>
<%= form_for (@mixtape) do |f| %>
 <%= @tracksamount.times do |i| %>
  <%= f.fields_for :songs, [Song.new] do |track| %>
  <li class="trackitem">
	<%= track.label :trackid %>
	<%= track.number_field :trackid, :readonly => true, :value => i + 1 %>
    <br />
	<%= track.label :title %>
	<%= track.text_field :title %>
	<br />
	<%= track.file_field :audio %>
  </li>
 <% end %>

 
<% end %>

  <%= f.label :archive %>
  <%= f.file_field :archive %><br />
<%= f.submit :class => "submit-button" %>
<% end %>
</ul>
<%= link_to "Submit", mixtape_path(@mixtape) %>
</div>

app/views/mixtapes/home.html.erb
<div id="masterplayer">
<div id="bg" class="large-12 columns" style="background-color: lightgrey;"></div>

 
	 <div id="yieldcontainer" class="row large-12 columns float-center">
        <div id="indexpadding" class="alpha60"> 



			    <div id="spotlight" class="row large-6 medium-6 columns">
			    	<div class="h1corner">
			    	<div class="h1"><span class="float-right">Spotlight</span></div>
			    	</div>
			    </div>

	    <div id="mixtapeindexwrapper" class="row large-7 small-12 columns float-left">

					<div class="mixtapeindex float-center">
					  <% @mixtapes.each do |mixtape| %>
					    <div class="mixtapecontainer large-3 medium-3 small-4 columns float-left">
					       <%= link_to mixtape, method: :get do %>
						    <div class="avatarcontainer float-center">
						         <%= image_tag(mixtape.mixtape_av) %>
						    </div>
						    <div style="color: black;" class="indexlabel" align="center">
						    	<span id="indexmixtapetitle"><b><%= mixtape.title %></b></span></br>
						    	<span id="indexartistname"><%= mixtape.artist.name %></span>

						    </div>
						   <% end %>
						</div>
					  <% end %>
					</div>

	    </div>

<div style="height: 1000px; width: 500px;"></div>

        </div>
	 </div>

<%= render "layouts/footplayer" %>

</div>
<script type="text/javascript">
	$(document).ready(function() {
soundManager.stopAll();
	});
</script>

app/views/mixtapes/index.html.erb
<div id="masterplayer">
<div id="bg" class="large-12 columns" style="background-color: grey;"></div>
 <div id="yieldcontainer" class="row large-12 columns float-center">
        <div id="indexpadding" class="alpha60">

   <div id="mixtapeindexwrapper" class="row large-7 small-12 columns float-left">

					<div class="mixtapeindex float-center">
					  <% @mixtapes.each do |mixtape| %>
					    <div class="mixtapecontainer large-3 medium-3 small-4 columns float-left">
					       <%= link_to mixtape, method: :get do %>
						    <div class="avatarcontainer float-center">
						         <%= image_tag(mixtape.mixtape_av) %>
						         <div id="indexvotebar"><div id="indexlikebar" style="width: <%= ((mixtape.get_upvotes.size.to_f / (mixtape.get_upvotes.size.to_f + mixtape.get_downvotes.size.to_f)) * 100) %>%"></div></div>
						    </div>
						    <div style="color: black;" class="indexlabel" align="center">
						    	<span id="indexmixtapetitle"><b><%= mixtape.title %></b></span></br>
						    	<span id="indexartistname"><%= mixtape.artist.name %></span>

						    </div>
						   <% end %>
						</div>
					  <% end %>
					</div>

	    </div>
		<div class="row large-4 columns">
			<%= link_to "Add new mixtape", new_mixtape_path %>
		</div>


		</div>
 </div>
<%= render "layouts/footplayer" %>

</div>

app/views/mixtapes/new.html.erb
<div id="yieldcontainer" style="background-color: grey;">
<div class="row">
<%= form_for @mixtape do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %><br />

  <%= f.label :mixtapeav %>
  <%= f.file_field :mixtape_av %><br />


  <%= f.label :tracksamount %>
  <%= f.number_field :tracksamount %>

  <%= f.submit %>
<% end %>
</div>
</div>
<button class="button" type="button" data-toggle="example-dropdown">Toggle Dropdown</button>
<div class="dropdown-pane" id="example-dropdown" data-dropdown data-auto-focus="true">
  Example form in a dropdown.
  <form>
    <div class="row">
      <div class="medium-6 columns">
        <label>Name
          <input type="text" placeholder="Kirk, James T.">
        </label>
      </div>
      <div class="medium-6 columns">
        <label>Rank
          <input type="text" placeholder="Captain">
        </label>
      </div>
    </div>
  </form>
</div>

app/views/mixtapes/show.html.erb
<div id="masterplayer">
<div id="mbtitlecontainer">

<div id="mbtitlewrapper" class="hide-for-large">
 <div id="mbtitle">
   <div class="sm2-playlist">
    <div class="sm2-mbplaylist-target"><div id="mbtitlegrad"><ul class="sm2-playlist-bd"></ul></div></div>
   </div>
 </div>
</div>
 <div id="mbtitleshadow" class="hide-for-large"></div>

</div>
        <div id="headerwrapper" class="row large-12 columns">
        <div id="desktopblank" style="height: 80px;" class="row medium-12 columns show-for-medium"></div>
        <div id="mobileblank" style="height: 13px" class="row small-12 columns hide-for-medium"></div>
         <div id="mixtapeartist" class="row large-12 small-12 columns float-left"><b><%= link_to "#{@mixtape.artist.name}", artist_path(@artist) %></b>
         <div id="mbloginbtn" class="float-right"></div>
         <div id="mbloginbtn" class="float-right"></div>
         <div id="mbloginbtn" class="float-right"></div>
         </div>

              <div id="artistsmixtapeswrap" class="row large-9 small-9 columns float-right">
                                <% if @artistsmixtapes.present? %>
                  <% @artistsmixtapes.each do |mixtape| %>
                    <div class="mixtapecontainer byartist float-left">
                       <%= link_to mixtape, method: :get do %>
                      <div class="avatarcontainer float-center">
                           <%= image_tag(mixtape.mixtape_av) %>
                           <span class="titleshow show-for-large">
                           <%= mixtape.title %>
                           </span>
                      </div>

                     <% end %>
                  </div>
              <% end %>
                  <% end %>
              </div>


        </div>

        <div id="yieldcontainer" class="row large-12 columns float-center" style="
    background: -webkit-linear-gradient(left top, rgba(0, 0, 0, 0.8), black 40%), url('<%= @mixtape.mixtape_av.url %>');
    background: -o-linear-gradient(bottom right, rgba(0, 0, 0, 0.8), black 40%), url('<%= @mixtape.mixtape_av.url %>');
    background: -moz-linear-gradient(bottom right, rgba(0, 0, 0, 0.8), black 40%), url('<%= @mixtape.mixtape_av.url %>');
    background: linear-gradient(to bottom right, rgba(0, 0, 0, 0.8), black 40%), url('<%= @mixtape.mixtape_av.url %>');">
        <script type="text/javascript">

          if ($(window).width() < 800) {
            $("#yieldcontainer").css("background-position", "center top");
            $("#yieldcontainer").css("background-size", "contain");
            $("#yieldcontainer").css("background-image", "linear-gradient(rgba(0, 0, 0, 0.8), black 100vh), url('<%= @mixtape.mixtape_av.url %>')");
            $("body").css("background-attachment", "scroll")
          }

        </script>



        <div id="contentpadding">


        <div id="labelwrapper" class="row large-12 small-12 columns float-right">
                <div id="leftcontainer" class="row large-3 medium-3 small-3 columns float-left">
                            <div id="mixtape_avcontainer">
                                <div class="float-left" id="mixtape_av">
                        			<%= image_tag(@mixtape.mixtape_av, :id => "mixtape_avimg") %>

                                </div>
                            </div>
                </div>


            	<div id="mixtapelabelcont" class="row large-9 columns">


                	<span id="mixtapetitle"><%= @mixtape.title %></span> <br />
                  <div id="mbmixtapedet" class="row large-5 small-5 columns float-left hide-for-large">
                  <span class="float-left viewscount"><%= image_tag("viewseye", :id => "viewseye") %><b><%= "#{@mixtape.impressionist_count}" %> <%= image_tag("dls") %><%= @mixtape.downloadscount.to_i %></b></span>
                  </div>


                  <span class="viewscount row large-5 columns float-left show-for-large"><%= image_tag("viewseye", :id => "viewseye") %><b><%= "#{@mixtape.impressionist_count}" %> <%= image_tag("dls") %><%= @mixtape.downloadscount.to_i %></b></span>

              </div>

        </div>

            <div id="playercontainer" class="row large-7 columns float-left">
            <%= render 'player' %>
            </div>
        <span class="row float-left hide-for-medium"><%= link_to 'Download mixtape', download_path(@mixtape), :class => "downloadbtn mb" %></span>

            <div id="disqustrigger" class="row small-12 columns show-for-small-only">SHOW COMMENTS</div>
                    <div id="disqus_thread" class="row large-7 columns float-left"></div>
                    <script>

                    /**
                     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
                     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables */
                    /*
                    var disqus_config = function () {
                        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
                        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
                    };
                    */
                    (function() { // DON'T EDIT BELOW THIS LINE
                        var d = document, s = d.createElement('script');
                        s.src = '//tapecamp.disqus.com/embed.js';
                        s.setAttribute('data-timestamp', +new Date());
                        (d.head || d.body).appendChild(s);
                    })();
                    </script>
                    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>


            <script type="text/javascript">
                        if ($(window).width() < 800) {
                            $("#yieldcontainer").css("padding-bottom", "60px")
                            $("#disqus_thread").css("display", "none");
                            $("#disqustrigger").click(function() {
                                  $("#disqus_thread").css("display", "block");
                            });
                          }

            </script>

        </div>
        </div>
        <%= render "layouts/footplayer" %>
</div>
</div>