config/routes.rb
Rails.application.routes.draw do

devise_for :artists, :controllers => { :registrations => 'artists/registrations' }

resources :artists do
resources :mixtapes do
	resources :songs
    get :autocomplete_mixtape_title, :on => :collection
	member do
		put "upvote", to: "mixtapes#upvote"
		put "downvote", to: "mixtapes#downvote"
end

get '/download', to: 'mixtapes#download'
end
end

resources :songs

resources :mixtapes

root 'mixtapes#home'

get '/download', to: 'mixtapes#download'

get '/singles', to: 'songs#index'

get "search/query"

get 'search/results', to: 'search#results'

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :mixtape
  mount_uploader :audio, AudioUploader
  validates_presence_of :audio

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :find_song, only: [:destroy]
  before_action :find_mixtape, only: [:create, :destroy]


   def index
    @allsongs = Mixtape.all.songs.all
   end

   def create
   	@mixtape = Mixtape.find(params[:mixtape_id])
   	@song = @mixtape.songs.create(song_params)
    @song.audio = params[:fog]

   	if @song.save
   		redirect_to edit_mixtape_path(@mixtape)
    else
      redirect_to edit_mixtape_path(@mixtape)
   	end
   end
   
   def destroy
     if @song.destroy
     redirect_to edit_mixtape_path(@mixtape)
   end
   end



private

    def song_params
     params.require(:song).permit(:title, :trackid, :audio) 	
    end   
    
    def find_mixtape
     @mixtape = Mixtape.find(params[:mixtape_id])
    end

    def find_song
      @mixtape = Mixtape.find(params[:mixtape_id])
      @song = @mixtape.songs.find(params[:id])
    end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/index.html.erb
<% if @allsongs.present? %>
   <% @allsongs.each do |song| %>
   <%= song.trackid %>
   <%= song.title %>   <br />
<% end %>
<% end %>

<%= link_to "Submit", mixtape_path(@mixtape) %>

app/views/songs/new.html.erb
<%= form_for([@mixtape, @mixtape.songs.build]) do |f| %>
	<%= f.label :trackid %>
	<%= f.number_field :trackid %>
    <br />
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br />
	<%= f.file_field :audio %>
	<%= f.submit %>
<% end %>