config/routes.rb
Rails.application.routes.draw do

devise_for :artists, :controllers => { :registrations => 'artists/registrations' }

resources :artists do
resources :mixtapes do
	resources :songs
    get :autocomplete_mixtape_title, :on => :collection
	member do
		put "upvote", to: "mixtapes#upvote"
		put "downvote", to: "mixtapes#downvote"
end

get '/download', to: 'mixtapes#download'
end
end

resources :songs

resources :mixtapes

root 'mixtapes#home'

get '/download', to: 'mixtapes#download'

get '/singles', to: 'songs#index'

get "search/query"

get 'search/results', to: 'search#results'

end

app/views/layouts/_footplayer.html.erb
<div id="footercontainer">
<footer>
    <div id="footerbarwrapper">
        <div id="footeroverlay" class="show-for-large">
        <div id="footerbaroverlay"></div><div id="footerprogball"><%= image_tag('progball') %></div>
        <div id="footeractivebar">
        </div>
        </div>
        <div id="footerprogballbl"><%= image_tag('progballbl') %></div>
    <script type="text/javascript">
    var wrapper = document.getElementById('footerbarwrapper');
    wrapper.onclick = function handlefooterMouse(e){};
    </script>
      <div id="footerbar">
      <div id="footerprogbar"></div>
      </div>
    </div>
</footer>

<footer>
      <div id="footercontrolwrapper" class="sm2-bar-ui fixed full-width flat">
      <div id="footerfrozen"></div>
     <div id="footercontrol" class="row bd sm2-main-controls">
      <div class="sm2-inline-texture"></div>
      <div class="sm2-inline-gradient"></div>
      <div class="sm2-inline-element hide-for-medium" id="ftmixtapeav">
      <% if @mixtape.present? %>
      <%= image_tag(@mixtape.mixtape_av) %>
      <% else %>
      <%= image_tag("logoxmmini") %>
      <% end %>
      </div>

      <div class="sm2-inline-element float-left">
        <div id="fttime" class="sm2-ftinline-time">0:00</div>
      </div>


      <div class="sm2-inline-element sm2-button-element float-left">
       <div class="sm2-button-bd">
        <a href="#prev" title="Previous" class="sm2-inline-button previous">&lt; previous</a>
       </div>
      </div>

      <div class="sm2-inline-element sm2-button-element float-left">
       <div class="sm2-button-bd">
        <a href="#play" class="sm2-inline-button play-pause">Play / pause</a>

       </div>
      </div>

      <div class="sm2-inline-element sm2-button-element float-left">
       <div class="sm2-button-bd">
        <a href="#next" title="Next" class="sm2-inline-button next">&gt; next</a>
       </div>
      </div>

      <div id="fttitle" class="float-left show-for-large" >
          <div class="sm2-ftplaylist-target"></div>
      </div>


      <div class="sm2-inline-element float-right">
        <div id="footerduration" class="sm2-ftinline-duration">0:00</div>
      </div>

  <div id="volumecontainer" class="show-for-large">


      <div class="sm2-inline-element float-right"  style="width: 100px; height: 40px; padding-top: 5px;">



        <div id="volumebarwrapper" class="sm2-volume-control" style="height: 100%;">
            <div id="volumebar" class="sm2-volume-control">
              <div id="volumebarfill">
              </div>
            </div>    
        </div>

      </div>

      <a id="volumeicon" class="sm2-inline-element float-right volume-3">
      </a>

  </div>
  
     </div>

    </div>

</footer>
</div>


  <div id="footershadow"><div id="footershadowrow" class="row show-for-medium"></div></div>


<script type="text/javascript">
  $('#footercontainer').mouseenter(function() { $('#footeroverlay').fadeIn(100); });
  $('#footercontainer').mouseleave(function() { $('#footeroverlay').fadeOut(100); });

  $('#volumeicon').click(function() {
     if (('sound0').muted) {
      soundManager.unmute('sound0');
     } else {
      soundManager.toggleMute('sound0');
     };

      $('#volumebarfill').toggleClass('muted');
      $(this).toggleClass('muted');
      
  });

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">

    <title><%= content_for?(:title) ? yield(:title) : if @mixtape.present?
      "#{@mixtape.title} - xMixtapes"
      else
      "xMixtapes"
      end %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= stylesheet_link_tag    "bar-ui" %>
    <%= stylesheet_link_tag    "customstyles" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "soundmanager2", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>



</head>



  </head>

  <body style="background-image: url(<%=
            @background %>)">
      
        <div id="navbar" class="show-for-medium">
        <div id="navbaroverlay" class="row large-12 columns">

        <%= link_to "sign out", destroy_artist_session_path, :method => :delete %>
             <div id="searchwrapper" class="large-3 medium-3 columns show-for-large float-right">
                      <%= form_tag search_results_path, :method => :get do %>
                          <%= text_field_tag :search, params[:search], :id => "searchinput", :class => "float-left", :placeholder => "Search Mixtapes..." %>
                          <%= image_submit_tag("search", :id => "searchbutton", :class => "float-left") %>
                      <% end %>
             </div>
        </div>
        </div>

          <%= yield %>

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  </body>

  <script type="text/javascript">
    $(document).foundation();
  </script>


</html>